name: Update DB entries
on:
  schedule:
    - cron: 0 0,6,12,18 * * *
  workflow_dispatch:
jobs:
  update_data:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=7168
    steps:
      - uses: actions/checkout@v2

      - name: Install Packages 🔧
        run: npm install

      - name: Update Data 🆕
        run: npm start
        env:
          REPO_AND_BRANCH: ${{ secrets.REPO_AND_BRANCH }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
